version: 2.1

jobs:
  test-and-analyze:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install requests pytest
      - run:
          name: Create test script
          command: |
            echo 'import requests' > test_script.py
            echo 'import json' >> test_script.py
            echo 'import os' >> test_script.py
            echo '' >> test_script.py
            echo '# Simulate test results' >> test_script.py
            echo 'test_results = {' >> test_script.py
            echo '    "status": "completed",' >> test_script.py
            echo '    "passed": 5,' >> test_script.py
            echo '    "failed": 2,' >> test_script.py
            echo '    "logs": "Test logs would go here..."' >> test_script.py
            echo '}' >> test_script.py
            echo '' >> test_script.py
            echo '# Call your Agentic AI API' >> test_script.py
            echo 'try:' >> test_script.py
            echo '    ai_response = requests.post(' >> test_script.py
            echo '        "https://backend-az2r.onrender.com/analyze-logs",' >> test_script.py
            echo '        json={"test_results": test_results},' >> test_script.py
            echo '        timeout=30' >> test_script.py
            echo '    )' >> test_script.py
            echo '    ai_analysis = ai_response.json()' >> test_script.py
            echo 'except Exception as e:' >> test_script.py
            echo '    ai_analysis = {"error": str(e), "analysis": "AI analysis failed"}' >> test_script.py
            echo '' >> test_script.py
            echo '# Post to Confluence' >> test_script.py
            echo 'try:' >> test_script.py
            echo '    confluence_data = {' >> test_script.py
            echo '        "space_key": "TEST",' >> test_script.py
            echo '        "page_title": "Test Results - CircleCI",' >> test_script.py
            echo '        "content": f"## Test Results Summary\\n- Passed: {test_results[\"passed\"]}\\n- Failed: {test_results[\"failed\"]}\\n\\n## AI Analysis\\n{ai_analysis.get(\"analysis\", \"No analysis available\")}\\n\\nGenerated by CircleCI"' >> test_script.py
            echo '    }' >> test_script.py
            echo '    requests.post(' >> test_script.py
            echo '        "https://backend-az2r.onrender.com/save-to-confluence",' >> test_script.py
            echo '        json=confluence_data,' >> test_script.py
            echo '        timeout=30' >> test_script.py
            echo '    )' >> test_script.py
            echo '    print("✅ Posted to Confluence successfully")' >> test_script.py
            echo 'except Exception as e:' >> test_script.py
            echo '    print(f"❌ Failed to post to Confluence: {e}")' >> test_script.py
            echo '' >> test_script.py
            echo 'print("🎉 Test and analysis completed!")' >> test_script.py
      - run:
          name: Run tests and analyze with AI
          command: python test_script.py
      - store_artifacts:
          path: test_script.py
          destination: test-artifacts

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-and-analyze 